### ISSUE TITLE
websdr@40.service

### ISSUE THREAD

**Issue by nicephore** [reynico/raspberry-websdr#1]
Hi

websdr@40.service

Bruno - F1TRN

**Comment by nicephore** [comment]
Thanks
And coold you send me the websdr@80.service

**Comment by reynico** [comment]
Hi!
[websdr@.service](https://github.com/reynico/raspberry-websdr/blob/master/etc/systemd/system/websdr%40.service) is a dynamic systemd unit, meaning that it accepts a parameter after the `@` symbol and passes the parameter to the unit itself. So there's no "websdr@40.service" file (or any other band-specific file), rather you just start it (as long as you've copied the [websdr@.service](https://github.com/reynico/raspberry-websdr/blob/master/etc/systemd/system/websdr%40.service) into `/etc/systemd/system/`)

for 160m reception:
> `sudo systemctl start websdr@160.service`

for 80m reception:
> `sudo systemctl start websdr@80.service`

for 40m reception:
> `sudo systemctl start websdr@40.service`
